### ISSUE TITLE
from phy.io import KwikModel Gives Error

### ISSUE THREAD

**Issue by lonilonbalon** [kwikteam/phy-doc#16]
Hi I think that in the newer version taking data out of the kwik file doesn't work the same way.
I'll be happy to know how 

Error: from phy.io import KwikModel
ImportError: cannot import name 'KwikModel'

**Comment by rossant** [comment]
it is

```
from klusta.kwik import KwikModel
```

the implementation of the kwik format has been moved into the [klusta](http://klusta.readthedocs.org/en/latest/) package
