### ISSUE TITLE
Various remarks on the quick start guide

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy-doc#8]
- maybe remove `This will install miniconda (a lightweight scientific Python distribution) and phy in your $HOME/miniconda by default (normally /home/username/miniconda on Linux/Mac OS X, and C:\Users\Username\miniconda\ on Windows).` and duplicate it 3 times for the 3 OSes, with the appropriate instructions
- to be more newbie-friendly I'd also add "open a terminal and copy-paste the following command". A dumb Windows user might not understand they need to do that

**Comment by rossant** [comment]
- at the end of the quick install, put a link to the quick start guide, otherwise, clicking on next leads to the advanced install guide

**Comment by rossant** [comment]
- The default value of 500 clusters in KK2 is way too large for the sample data so KK2 is quite slow. The PRM file should be modified to have a smaller value

**Comment by nippoo** [comment]
is that a phy-doc issue?

**Comment by nippoo** [comment]
also yeah - will do - with PowerShell not cmd!
